### ISSUE TITLE
Are you still working on this?

### ISSUE THREAD

**Issue by elsholz** [felixwo/tracksquared#3]
Hey I wonder, what is the goal of this project, are you still working on this or the concept behind it at least?

**Comment by timgrohmann** [comment]
Hallo Hendrik. Du kannst natürlich auch mit uns/mir sprechen, aber ein Issue in GitHub tut es natürlich auch.
Prinzipiell war/ist das Ziel, Bahnreisen langfristig zu tracken und analysieren. Aktuell habe ich aber nicht wirklich Zeit, daran zu arbeiten.
